apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: k8s-cluster-state
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: k8s-cluster-state
    spec:
      containers:
      - name: k8s-cluster-state
        image: talberto/k8s-cluster-state
        env:
        - name: K8S_POLLING_INTERVAL
          value: "1000"
        - name: K8S_CLIENT_TYPE
          value: "poll"
        - name: RABBITMQ_EXCHANGE
          value: "k8s-cluster-queue"
        - name: RABBITMQ_HOST
          value: "rabbitmq"
        - name: RABBITMQ_USERNAME
          value: "guest"
        - name: RABBITMQ_PASSWORD
          value: "guest"
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
